updated the logic

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -21,11 +21,6 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v3
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: '14'
-
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
 
@@ -36,55 +31,50 @@ jobs:
           push: false
           tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:pr-test
 
-  build_and_test:
-    runs-on: ubuntu-latest
-    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
-
-      - name: Build Docker image
-        uses: docker/build-push-action@v3
-        with:
-          context: .
-          push: false
-          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:build-test
-
   version_bump:
     runs-on: ubuntu-latest
-    needs: build_and_test
+    needs: pr_check
+    if: github.ref != 'refs/heads/main'
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
         with:
           fetch-depth: 0
 
-      - name: Get current version
-        id: get_version
-        run: echo "::set-output name=current_version::$(cat VERSION)"
-        
-      - name: Increment version
-        id: increment_version
+      - name: Check if commit is already tagged and create new tag if necessary
+        id: tag_commit
         run: |
-          current_version=${{ steps.get_version.outputs.current_version }}
-          new_version=$(echo $current_version | awk -F. '{printf("%d.%d.%d", $1, $2, $3+1)}')
-          echo "New version: $new_version"
-          echo $new_version > VERSION
-          git config --global user.email "github-actions[bot]@users.noreply.github.com"
-          git config --global user.name "github-actions[bot]"
-          git add VERSION
-          git commit -m "Bump version to $new_version"
-          git tag $new_version
-          git push https://${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }} HEAD:main --follow-tags
+          echo "Checking if the commit is already tagged"
+          if ! git describe --tags --match "v*" --exact-match $GITHUB_SHA 2>&1 | grep "fatal"; then
+            git describe --tags --match "v*" --abbrev=0 --exact-match $GITHUB_SHA > tag.txt
+            echo "Commit is already tagged, using tag: $(cat tag.txt)"
+          else
+            echo "Getting previous tag"
+            CURRENT_TAG=$(git describe --tags --match "v*" --abbrev=0)
+            if [ "${CURRENT_TAG}" = "" ]; then
+              echo "Can't find any tags"
+              NEW_TAG="v1.0.0"
+            else
+              echo "Increment minor version"
+              NEW_TAG=$(echo "${CURRENT_TAG}" | awk -F'[v.]' '{print "v"$2"."$3+1"."$4}')
+            fi
+            echo "$NEW_TAG" > tag.txt
+            echo "Current tag is ${CURRENT_TAG}"
+            echo "New tag is ${NEW_TAG}"
+            echo "Creating new tag"
+            git tag "${NEW_TAG}"
+            echo "Saving new tag to VERSION file"
+            echo "${NEW_TAG}" > VERSION
+            git add VERSION
+            git commit -m "Bump version to ${NEW_TAG}"
+            git push origin HEAD:$(git rev-parse --abbrev-ref HEAD)
+            git push origin "${NEW_TAG}"
+          fi
         shell: bash
 
   build_and_push:
     runs-on: ubuntu-latest
+    if: github.ref == 'refs/heads/main'
     needs: version_bump
     permissions:
       contents: read
